# -*- coding: utf-8 -*-
"""optimasi model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RhhwFz43w4yLAPpXqCrlnUtcTO4np6DS
"""

param_grid = {
    'Learning Rate': [0.01, 0.1, 1],
    'Jumlah Neuron': [10, 50, 100]
}

import numpy as np

param_dist = {
    'C': np.logspace(-2, 2, 10),  # C = 0.01 sampai 100
    'gamma': np.logspace(-4, 1, 10),  # Gamma = 0.0001 sampai 10
    'kernel': ['rbf']  # Kernel tetap menggunakan 'rbf'
}